import { NextPage } from 'next';
import Head from 'next/head';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <h1>About</h1>
    </>
  );
};

export default About;
