import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <h1>Projects</h1>
      <p>Take a look at some of my projects</p>

      <article>
        <Link href='#'>
          <a>
            <h1>NTNU plant manager</h1>
          </a>
        </Link>
      </article>

      <article>
        <Link href='#'>
          <a>
            <h1>NTNU plant manager</h1>
          </a>
        </Link>
      </article>

      <article>
        <Link href='#'>
          <a>
            <h1>NTNU plant manager</h1>
          </a>
        </Link>
      </article>
    </>
  );
};

export default Projects;
