import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { FiAward, FiGithub, FiLinkedin, FiMail } from 'react-icons/fi';

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Get in touch</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <h1>Get in touch</h1>
      <p>Take a look at some of my projects</p>

      <address>
        <ul>
          <li>
            <Link href='#' target='_blank' rel='noreferrer'>
              <a>
                <FiLinkedin /> LinkedIn
              </a>
            </Link>
          </li>
          <li>
            <Link href='#' target='_blank' rel='noreferrer'>
              <a>
                <FiGithub /> Github
              </a>
            </Link>
          </li>
          <li>
            <Link href='#'>
              <a>
                <FiMail /> Email
              </a>
            </Link>
          </li>
          <li>
            <Link href='#' target='_blank' rel='noreferrer'>
              <a>
                <FiAward /> Resume
              </a>
            </Link>
          </li>
        </ul>
      </address>

      <form>
        <label htmlFor='name'>Name</label>
        <input type='text' name='name' id='name' />

        <label htmlFor='email'>Email</label>
        <input type='email' name='email' id='email' />

        <label htmlFor='message'>Message</label>
        <textarea name='message' id='message'></textarea>

        <button type='submit'>Send message</button>
      </form>
    </>
  );
};

export default Contact;
